name: ups_education
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_screenutil: ^5.6.0
  smooth_page_indicator: ^1.0.0+2
  url_launcher: ^6.1.7
  any_link_preview: ^2.0.9
  get_storage: ^2.0.3
  flutter_svg: ^1.1.6
  metadata_fetch: ^0.4.1
  dio: ^4.0.6
  flutter_widget_from_html_core: ^0.9.1
  cached_network_image: ^3.2.3
  youtube_plyr_iframe: ^2.0.7
  webview_flutter: ^4.0.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/fonts/
  
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 800
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700

